In [2]:
import numpy as np

In [ ]:
arr1 = np.array([[1, 2, 3],[7, 8, 9]])
arr2 = np.array([4, 5, 6])

added_arr = arr1 + arr2
multiplied_arr = arr1 * arr2
 
print(added_arr, "\n", multiplied_arr)

[[ 5  7  9]
 [11 13 15]] 
 [[ 4 10 18]
 [28 40 54]]


In [4]:
print(np.dot(arr1, arr2))

[ 32 122]
