In [1]:
import numpy as np

In [16]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 10000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("==== Zomato sales analysis ==== ")
print("\n Sales data shape", sales_data.shape)
print("\n First two sales", sales_data[:3])

==== Zomato sales analysis ==== 

 Sales data shape (5, 5)

 First two sales [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000  10000]
 [     3 200000 230000 260000 300000]]


In [17]:
min_sales = np.min(sales_data[:, 1:], axis=1)
print(min_sales)

[150000  10000 200000 180000 160000]
